export const APP_STORE_ERROR = 'APP_STORE_ERROR';
export const REQUEST_FAILED = 'REQUEST_FAILED';


export const CREATE_DONATION_REQUEST = 'CREATE_DONATION_REQUEST';
export const CREATE_DONATION_REQUEST_SUCCESS = 'CREATE_DONATION_REQUEST_SUCCESS';

export const FETCH_DONATION_REQUEST = 'FETCH_DONATION_REQUEST';
export const FETCH_DONATION_REQUEST_SUCCESS = 'FETCH_DONATION_REQUEST_SUCCESS';

export const CONFIRM_REQUEST = 'CONFIRM_REQUEST';
export const CONFIRM_REQUEST_SUCCESS = 'CONFIRM_REQUEST_SUCCESS';

export const FETCH_HELPING_HANDS = 'FETCH_HELPING_HANDS';
export const FETCH_HELPING_HANDS_SUCCESS = 'FETCH_HELPING_HANDS_SUCCESS';


export const RAISE_NEED_REQUEST = 'RAISE_NEED_REQUEST';
export const RAISE_NEED_REQUEST_SUCCESS = 'RAISE_NEED_REQUEST_SUCCESS';

export const FETCH_NEEDS = 'FETCH_NEEDS';
export const FETCH_NEEDS_SUCCESS = 'FETCH_NEEDS_SUCCESS';

export const FETCH_DONARS = 'FETCH_DONARS';
export const FETCH_DONARS_SUCCESS = 'FETCH_DONARS_SUCCESS';

export const CONFIRM_NEED_REQUEST = 'CONFIRM_NEED_REQUEST';
export const CONFIRM_NEED_REQUEST_SUCCESS = 'CONFIRM_NEED_REQUEST_SUCCESS';


export const ADD_REQUEST = 'ADD_REQUEST';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';
export const GET_DONARS_REQUEST_STATUS = 'GET_DONARS_REQUEST_STATUS';
export const CLEAR_RESPONSE_MESSAGE = 'CLEAR_RESPONSE_MESSAGE';



export const API_SUFFIX = {
    SUCCESS: '_SUCCESS',
    IN_PROGRESS: '_IN_PROGRESS',
    FAILURE: '_FAILURE'
};

export function appStoreError(error) {
    return {
        type: APP_STORE_ERROR,
        payload: {
            ...error
        }
    };
}